CREATE TABLE `waiter` (
	`AUTO_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`FIRST_NAME` VARCHAR(60) NULL DEFAULT NULL,
	`LAST_NAME` VARCHAR(60) NULL DEFAULT NULL, 
	`DOB` VARCHAR(16) NULL DEFAULT NULL,
	PRIMARY KEY (`AUTO_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
